version: "3.9"

services:
 stealer-app:
 build: . # Uses Dockerfile in repo root
 image: 365-stealer-app:latest
 ports:
 - "80:80" # Exposes HTTP to the world
 # Remove this in production unless you really need live-mount:
 # volumes:
 # - .:/var/www/html
 restart: unless-stopped
 networks:
 - reee-net

networks:
 reee-net:
 driver: bridge
