version: "3.9"

services:
 stealer-app:
 build:
 context: . # directory where Dockerfile + app code live
 image: 365-stealer-app:latest
 ports:
 - "8080:80" # host:container
 restart: unless-stopped
 networks:
 - reee-net

networks:
 reee-net:
 driver: bridge
