version: "3.9"

services:
 stealer-app:
 build: .
 image: 365-stealer-app:latest
 ports:
 - "8080:80" # Host 8080 -> container 80
 restart: unless-stopped
 networks:
 - reee-net

networks:
 reee-net:
 driver: bridge
